version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    environment:
      BUILD_IMAGE: gcr.io/plasma-column-128721/ros-builder:arm64v8-1.0.2
    steps:
     - checkout
     - restore_cache:
         keys:
           - build-ccache-pcl-global
     - run:
         name: Auth google project
         command: |
           echo ${CLIENT_SECRET} | base64 --decode > ${HOME}/client-secret.json
           gcloud auth activate-service-account --key-file ${HOME}/client-secret.json
           gcloud config set project ${GCLOUD_PROJECT}
     - run:
         name: Pull docker image from gcloud
         command: gcloud docker -- pull $BUILD_IMAGE
     - run:
         name: Run build
         no_output_timeout: "2h"
         command: |
            docker run -v $PWD:/workspace -e CCACHE_DIR=/mfp_workspace/.ccache -it $BUILD_IMAGE /bin/bash -C "/workspace/.circleci/build.sh"
     - save_cache:
         key: build-ccache-pcl-global-{{ epoch }}
         paths:
           - output/.ccache
         when: always
